---
version: '3.4'

networks:
  n2pool:
    driver: bridge

volumes:
  n2pool: 

    name: n2pool



  monero:
    name: monero


services:
  n2pool:
    image: n2pool:latest
    build: ../
    container_name: n2pool-n2pool
    networks:
      - n2pool
    privileged: true
    ports:

      - 41519:41519/tcp


    volumes:
      - n2pool:/home/n2pool/.n2pool:rw
      - /dev/null:/home/n2pool/.n2pool/n2pool.log:rw
      - /dev/hugepages:/dev/hugepages:rw

    depends_on:
      - monero

    restart: unless-stopped
    command: >-

      --host monero

      --wallet 44MnN1f3Eto8DZYUWuE5XZNUtE3vcRzt2j6PzqWpPau34e6Cf4fAxt6X2MBmrm6F9YMEiMNjN6W4Shn4pLcfNAja621jwyg
      --loglevel 3



      --local-api
      --data-api /home/n2pool/.n2pool








  statistics:
    image: statistics:latest
    build:
      context: statistics
    container_name: n2pool-statistics
    networks:
      - n2pool
    ports:
      - 3380:80/tcp
    volumes:
      - n2pool:/data:ro
    depends_on:
      - n2pool
    restart: unless-stopped




  monero:
    image: monero:latest
    build:
      context: monero
      args:
        - MONERO_GIT_TAG=latest
    container_name: n2pool-monero
    networks:
      - n2pool
    ports:
      - 18080:18080/tcp

    volumes:
      - monero:/home/monero/.bitmonero:rw
      - /dev/null:/home/monero/.bitmonero/bitmonero.log:rw
      - /dev/hugepages:/dev/hugepages:rw
    restart: unless-stopped
    command: >-
      --zmq-pub tcp://0.0.0.0:44233
      --disable-dns-checkpoints
      --enable-dns-blocklist
      --out-peers 16
      --in-peers 32
      --add-priority-node=nodes.hashvault.pro:18080
      --add-priority-node=p2pmd.xmrvsbeast.com:18080
      --non-interactive
      --p2p-bind-ip=0.0.0.0
      --p2p-bind-port=18080
      --rpc-bind-ip=0.0.0.0
      --rpc-bind-port=44231
      --restricted-rpc
      --confirm-external-bind
      --log-level=0

      --prune-blockchain





      --fast-block-sync=1






  xmrig:
    image: xmrig:latest
    build: xmrig
    container_name: n2pool-xmrig
    networks:
      - n2pool
    privileged: true
    volumes:
      - /dev:/dev:ro
      - /lib/modules:/lib/modules:ro
      - /dev/hugepages:/dev/hugepages:rw
    depends_on:
      - n2pool
    restart: unless-stopped
    command: >-
      --randomx-1gb-pages
      -o n2pool:3333

      -u n2pool

      --cpu-max-threads-hint=100
      --cpu-priority=2

